### ISSUE TITLE
4.2.3 Breaks for-in loops on arrays

### ISSUE THREAD

**Issue by nik-markovic** [RIAEvangelist/event-pubsub#11]
Hi,

We found this issue with node 4.3.2 and event-pubsub 4.2.3  while using node-ipc, which requires your library.

```
require('event-pubsub');
var arr = [1,2,3];
for (var i in arr) {
    console.log(i);
}
```

Output:

```
0
1
2
includes
```

I think that one of the es*.js files is injecting something that interferes with the for/in loops.

Edit: I understand that using for/in to loop arrays may not be a correct thing to do, however this issue is causing problems with other libraries, which otherwise work.

Thanks,
Nik

**Comment by RIAEvangelist** [comment]
which version of node?

for in is fine to do, but depending on the verison of node, you should be checking has own property or something similar. This is standard practice in JS with for in.

I'll take a look.

**Comment by nik-markovic** [comment]
I specified already: node 4.3.2 - it can get confusing because the event-pubsub version is similar.

And yes, one can use hasOwnProperty to ensure the correct iteration. It's just that user typically controls their own structures and data and (foolishly) makes assumptions that the data in their own objects/arrays contains only what they put in.

We have solved the issues on our end, by the way by correcting our code. I am not sure if many other users would encounter a similar problem because they, like us, used unsafe loops. It is really up to you to decide what you want to do. I am just pointing out the issue, and I am perfectly happy with you deciding not to change your library.

**Comment by RIAEvangelist** [comment]
I will check the performance hit of polyfilling array without having includes visible.

Thanks!

**Comment by RIAEvangelist** [comment]
@nik-markovic are you saying there is an issue with ` node-ipc ` because of this?

**Comment by RIAEvangelist** [comment]
I think I have found a way for the performance impact of hiding the ` includes ` key to be limited to systems running node or browsers which do not natively support this functionality.
