### ISSUE TITLE
Token method of unsubscribing

### ISSUE THREAD

**Issue by j2is** [RIAEvangelist/event-pubsub#17]
Would it be possible to add a feature where you can create a token when subscribing to a topic, and use that token to unsubscribe later on? Chaining isn't a good option for me as I unsubscribe at a different point in my app, not when the topic is received. Here's an example of an ideal syntax, showing the added advantage of allowing short arrow functions:

```

var subscriptions = [];
subscriptions.push(events.on('foo', ()=> {
  // function 1
));
subscriptions.push(events.on('bar', ()=> {
  // function 2
)));

for (var token of subscriptions) {
  events.off(token);
}

```
Currently the cleanest way to do the same thing is less concise (unless you can see a better way):

```
var subscriptions = [];

var function1 = ()=> {};
var function2 = ()=> {};
subscriptions.push({type: 'foo', handler: function1});
subscriptions.push({type: 'bar', handler: function2});
events.on('foo', function1);
events.on('bar', function2);

for (var token of subscriptions) {
  events.off(token.type, token.handler);
}
```
I'm aware there is a wildcard * but this would cancel all subscriptions to that topic, even if there are other parts of the application that might still need the topic (for example subscribers to a scroll event)

**Comment by RIAEvangelist** [comment]
you can just unbind them all if you want. Only pass in the type, it will remove all the handlers.
