### ISSUE TITLE
Don't patch `Array.prototype.includes`

### ISSUE THREAD

**Issue by jonschlinkert** [RIAEvangelist/event-pubsub#18]
I noticed this library in the dependencies of `node-ipc`, and was rather shocked to see that it implements a polyfill for `Array.prototype.includes`, which - beyond being unnecessary nothing in this library - is incomplete in its implementation and can potentially cause unwanted side-effects for unsuspecting implementors if this is bundled into production code. 

I'd greatly appreciate it if you could publish a patch to remove the polyfill so that it's no longer in my dependency tree.

**Comment by RIAEvangelist** [comment]
removed in v5.x
