### ISSUE TITLE
Is copyfiles a production dependency?

### ISSUE THREAD

**Issue by mckravchyk** [RIAEvangelist/event-pubsub#23]
The package has about [45 production dependencies](http://npm.anvaka.com/#/view/2d/event-pubsub) - almost all of which come from `copyfiles`. I ran a [search](https://github.com/RIAEvangelist/event-pubsub/search?q=copyfiles) and it seems like the package is only a part of of the `emulate` npm command.

Shouldn't this be a dev dependency? I'm using `node-ipc`  (which depends on `event-pubsub`) and it seems like all of these `copyfiles` dependencies are also a part of `node-ipc` dependencies, but they are not used at all by `node-ipc`, are they?

I'm doing a purge on the npm packages in my app to minimize the attack surface. I almost considered removing `node-ipc` due to the number of its dependencies, but then I realized most of them are part of `copyfiles` and are never executed . Fixing this would make `node-ipc` and other dependents more appealing to developers by lowering their number of dependencies.

**Comment by RIAEvangelist** [comment]
I would merge if you made a PR

**Comment by RIAEvangelist** [comment]
copyfiles appears to be a dev dependency already.

Can you confirm the issue?

**Comment by mckravchyk** [comment]
Apologies for the confusion. It indeed is. I don't know how I overlooked it. I could swore I checked package.json but it seems like either I didn't or overlooked it. The tool I used to analyze the dependencies must have been wrong.

**Comment by RIAEvangelist** [comment]
np. was good to check anyway. 🥳
