### ISSUE TITLE
Remove all events

### ISSUE THREAD

**Issue by roblinton** [RIAEvangelist/event-pubsub#3]
Hi,

Was `pubsub.off('*', '*')`meant to be supported?  The last commit appears to remove support for this use case.

Cheers,

Rob

**Comment by RIAEvangelist** [comment]
I believe this was removed intentionally. I will have a look.

**Comment by RIAEvangelist** [comment]
`events.off('*', '*')` will remove all events from the `*` event type which is fired for all events and handlers should accept `type,...arguments`

if you want to remove all events you should do so by removing them with `off('type','*')`
or with a for each on the events._events object

**Comment by roblinton** [comment]
This is fine, of course.  There is a bit of ambiguity between * meaning any event or all events (in off('*', '*') it means different things in either position) but I'm not sure it merits another symbol to differentiate.

Thanks for looking into it.

**Comment by RIAEvangelist** [comment]
:thumb:
