### ISSUE TITLE
Emit call does not allow otherwise unregistered events to propagate "*" handlers

### ISSUE THREAD

**Issue by mrvini** [RIAEvangelist/event-pubsub#7]
Emit call blocks even propagation in the case when event is not registered, or the listener only setup for on "*" event

As an example in es6.js file on line 57

```javascript
emit(type,...args){
        if(!this._events_[type]){
            return;
        }

        ......

```

**Comment by RIAEvangelist** [comment]
legit

**Comment by mrvini** [comment]
still an issue ,

need to pass the type of the event, otherwise, its lost
add before header.apply

```javascript
args.unshift(type);
handler.apply(this, args);
````
